version: "{build}"
image: Visual Studio 2017

install:

before_build:
  - cmd: dotnet --version

build_script:
  - cmd: build.cmd
  - cmd: tests\CodeCoverage\CodeCoverage.cmd

after_build:
  - cmd: appveyor PushArtifact "artifacts\SixLabors.Shapes.%APPVEYOR_BUILD_VERSION%.nupkg"
  - cmd: appveyor PushArtifact "artifacts\SixLabors.Shapes.Text.%APPVEYOR_BUILD_VERSION%.nupkg"

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/sixlabors/api/v2/package
    symbol_server: https://www.myget.org/F/sixlabors/symbols/api/v2/package
    api_key:
      secure: V/lEHP0UeMWIpWd0fiNlY2IgbCnJKQlGdRksECdJbOBdaE20Fl0RNL7WyqHe02o4
    artifact: /.*\.nupkg/
    on:
      branch: master
      
# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

test: off
